language: minimal

branches:
  only:
    - main  # or 'master' if your default branch is master

before_script:
  - echo "Preparing deployment..."

script:
  - echo "Build step (if needed) goes here"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # GitHub token from environment variables
  keep_history: true
  on:
    branch: main  # Deploy only when push happens to main
